spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/zcy166/spring-cloud-config
          search-paths: respo
          username: 1663588662@qq.com
          password: 8961694411X
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/




